"""
This is a very basic script to anonymise a show-tech file generated by a Cisco switch.
The script will remove all text from the key fields in the 'fields' dictionary and replaces it with the value belonging to the key.

It takes a filename as input on the cli and the output is the filename with -anon added to it.
The original file will be left unaltered.

I don't claim this software is good for anything. If you think it is, cool. If it doesn't work, that's too bad.
If you lose a million because it messes up your PC or server, it's you that loses a million, not me.
If you don't like this disclaimer, that's too bad.
I reserve the right to do the absolute minimum provided by law, up to and including absolutely nothing.

This is basically the same disclaimer that comes with all software packages
but this one is written in plain English, theirs is written in Legalese and BaffleGab.

I didn't want to include any disclaimer at all, but lawyers showed up and insisted.
I tried to ignore them but they threatened me with the License Agreement Ninjas.
"""

import os
import re
import sys

filename = sys.argv[-1]
tempfile = filename + "-tmp"
anonfile = filename + "-anon"
openfile = open(filename, "r")
savefile1 = open(tempfile, "w")
savefile2 = open(anonfile, "w")

"""
Now the declaration mambo-jambo is done, we can define all words in the input file we would like to be replaced.
Check the original show-tech file. Some parts, like snmp-server community and the community strings appear to be already
anonymised bij Cisco.
"""

fields = {"string-to-replace1": "<<ANONYMISED>>", "string-to-replace1": "<<ANONYMISED>>", "string-to-replace1": "<<ANONYMISED>>"}

for line in openfile:
    for i in fields:
        for field in fields:
            field_value = fields[field]

            if field in line:
                line = line.replace(field, field_value)

    savefile1.write(line)

openfile.close()
savefile1.close()

"""
Now that's done we can move on to removing all IP adresses in the file.
In the first part we made an intermittent file. We will use that as input for this stage.
We use regex to find the IP adresses
"""

openfile = open(tempfile, "r")

for line in openfile:
    line = re.sub(r'(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)', '<<ANONIMYSED IPV4>>', line)
    savefile2.write(line)

"""
Now we close allopen files and remove the intermittent one.
"""

openfile.close()
savefile2.close()
os.remove(tempfile)
